name: keycloak

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    command: start-dev
    ports:
      - 8083:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_PASSWORD: admin
      KC_DB_USERNAME: admin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fc-network
      - keycloak-internal

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: keycloak
    volumes:
      - .docker/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - keycloak-internal


networks:
  fc-network:
    external: true
  keycloak-internal:
    driver: bridge
